/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cepri_dev_IRDA */

#ifndef _Included_com_cepri_dev_IRDA
#define _Included_com_cepri_dev_IRDA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cepri_dev_IRDA
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    clearSendCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_clearSendCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    clearRevCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_clearRevCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    config
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_config
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    sendData
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    recvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_recvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    setTimeOut
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_setTimeOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    clearSendCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_clearSendCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    clearRevCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_clearRevCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    config
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_config
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    sendData
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    recvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_recvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_cepri_dev_LaserIRDA
 * Method:    setTimeOut
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LaserIRDA_setTimeOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_cepri_dev_LibInfo
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LibInfo_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_LibInfo
 * Method:    getCompany
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_LibInfo_getCompany
  (JNIEnv *, jclass);


/*
 * Class:     com_cepri_dev_Scanner
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Scanner_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Scanner
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Scanner_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Scanner
 * Method:    decode
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Scanner_decode
  (JNIEnv *, jclass, jint, jbyteArray, jint);


/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    clearSendCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_clearSendCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    clearRevCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_clearRevCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    config
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_config
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    sendData
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    recvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_recvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_cepri_dev_SecurityUnit
 * Method:    setTimeOut
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_SecurityUnit_setTimeOut
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    clearSendCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_clearSendCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    clearRevCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_clearRevCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    config
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_config
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    sendData
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    recvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_recvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_cepri_dev_IRDA
 * Method:    setTimeOut
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_IRDA_setTimeOut
  (JNIEnv *, jclass, jint, jint);

/* Class:     com_cepri_dev_Serialport
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_init
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    deInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_deInit
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    clearSendCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_clearSendCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    clearRevCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_clearRevCache
  (JNIEnv *, jclass);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    config
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_config
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    sendData
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_sendData
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    recvData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_recvData
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_cepri_dev_Serialport
 * Method:    setTimeOut
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cepri_dev_Serialport_setTimeOut
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
